spring.application.name=Integradora_spring_boot
jdbc:mysql://localhost:3306/integradora

# URL de la base de datos (puerto 3306 y nombre 'integradora')
spring.datasource.url=jdbc:mysql://localhost:3306/integradora?serverTimezone=UTC

# Credenciales (usa tu contraseña de MySQL Server)
spring.datasource.username=root
spring.datasource.password=Josenieto06#

# Configuración de JPA para crear/actualizar tablas automáticamente
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect